import type { Metadata } from "next";
import Stack from "@mui/material/Stack";
import "./globals.css";
import { List, ListItem, ListItemIcon, ListItemText } from "@mui/material";
import { NAVDATA } from "@/constants";
import TopBar from "@/components/layout/top-bar";

export const metadata: Metadata = {
  title: "Anyware software",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-100">
        <Stack direction="row">
          {/* Side bar -------------------------------------------------------------------------- */}
          <List className="bg-gradient-to-t from-cyan-500 via-cyan-700 to-customBlue">
            <h1 className="text-3xl font-bold place-self-center mb-12">
              Coligo
            </h1>
            {NAVDATA.map((item) => (
              <ListItem
                key={item.text}
                className="px-10 py-5 hover:bg-white hover:text-cyan-500 group"
              >
                <ListItemIcon className="text-white group-hover:text-cyan-500">
                  {item.icon}
                </ListItemIcon>
                <ListItemText primary={item.text} />
              </ListItem>
            ))}
          </List>
          <Stack className="w-full bg-gray-100">
           <TopBar />
            {children}
          </Stack>
        </Stack>
      </body>
    </html>
  );
}
